# 1. Create a 3x3x3 array with random values 

In [30]:
import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [57]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [17]:
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
Z

array([[0.41466314, 0.91526279, 1.        , 0.84118259, 0.55039172],
       [0.60330271, 0.92858945, 0.00587309, 0.18365579, 0.77109299],
       [0.43756713, 0.98125346, 0.42521953, 0.01385938, 0.9652004 ],
       [0.61342999, 0.25969065, 0.8601664 , 0.54962065, 0.29435022],
       [0.46139609, 0.        , 0.17733531, 0.21847575, 0.02366668]])

# 5.  How to find common values between two arrays?

In [26]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([7,8,9,10])
print(np.intersect1d(a,b))

[7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [1]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [9]:
a=np.array(np.arange(0,8))
a.reshape(4,2)
b=np.array(np.arange(0,8))
b.reshape(4,2)

print(a==b)

[ True  True  True  True  True  True  True  True]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [10]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[a.argmax()]=0
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

# 9. How to print all the values of an array?

In [11]:
c=np.array([1,2,3,5,6,7,8,9,22,3443,444])
for i in c:
    print(i,end=" ")

1 2 3 5 6 7 8 9 22 3443 444 

# 10.Subtract the mean of each row of a matrix

In [55]:
f=np.arange(9)
f=f.reshape(3,3)
print(f,"\n\n")
Y = f - f.mean(axis=1, keepdims=True)
Y





[[0 1 2]
 [3 4 5]
 [6 7 8]] 




array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [18]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 2. 6. 5. 2. 2. 2. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [17]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
e=np.dot(c,d)
e.diagonal()

array([19, 50])

# 13.How to find the most frequent value in an array?

In [5]:
import numpy as np
x = np.random.randint(0, 10, 400)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[5 9 3 0 6 5 0 2 5 8 0 5 0 2 7 7 2 0 0 0 2 4 0 6 5 4 7 0 4 2 4 3 0 6 7 5 8
 5 4 5 3 4 9 0 5 9 4 6 1 0 9 4 2 0 8 7 5 7 9 2 5 4 8 5 6 9 2 0 7 7 5 1 9 7
 7 6 7 9 5 5 3 6 3 1 2 6 9 5 1 6 5 7 7 4 0 8 0 4 8 4 2 5 1 4 1 4 2 8 5 9 0
 6 7 5 0 1 8 6 6 2 9 7 7 0 2 0 1 7 1 9 0 8 9 2 9 9 2 7 3 2 0 0 4 4 8 7 8 6
 4 7 2 8 0 4 9 4 4 7 3 9 7 5 7 1 4 2 1 3 9 0 4 1 8 3 4 1 3 0 0 6 5 0 5 8 4
 4 2 7 3 9 6 7 4 7 8 5 3 9 2 8 6 5 9 0 0 0 9 2 0 5 0 4 7 1 7 1 5 4 8 5 5 4
 9 6 4 9 5 1 3 3 6 9 2 9 5 3 7 1 6 3 1 1 4 0 5 5 1 4 4 9 3 9 3 0 7 5 7 5 6
 4 4 3 7 6 1 8 2 2 9 7 5 4 1 5 1 2 9 5 1 7 7 8 4 2 4 2 4 8 7 4 0 0 8 3 4 8
 5 5 0 6 6 9 5 4 9 9 0 4 8 7 0 8 2 5 0 0 1 8 0 4 0 6 7 5 0 0 3 1 8 0 8 1 6
 1 8 2 9 0 2 7 5 0 0 2 2 7 3 5 4 2 5 6 9 5 7 6 2 6 4 9 5 7 4 0 3 1 5 0 5 2
 8 8 1 0 3 8 4 7 2 4 2 8 5 9 6 5 9 8 4 9 6 8 0 6 3 6 2 0 8 8]
Most frequent value in the above array:
0


# 14.How to get the n largest values of an array

In [11]:
a=np.array([1,2,3,66,778,33,7458])

a[a.argmax()]

7458

# 15.How to create a record array from a regular array?

In [20]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')



In [21]:
print(Z)
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
